import { motion } from 'motion/react';
import { ArrowLeft, Download, AlertTriangle, CheckCircle, FileText } from 'lucide-react';
import { ScoreGauge } from '../ScoreGauge';
import { TimelineChart } from '../TimelineChart';
import { ModelConsensus } from '../ModelConsensus';
import { DetectionBreakdown } from '../DetectionBreakdown';
import { IssuesList } from '../IssuesList';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { useRef, useState } from 'react';

interface AnalysisResultsProps {
  data: any;
  onReset: () => void;
}

export function AnalysisResults({ data, onReset }: AnalysisResultsProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [generatingPDF, setGeneratingPDF] = useState(false);

  const getVerdictColor = (verdict: string) => {
    if (verdict.includes('HIGHLY')) return 'text-red-500';
    if (verdict.includes('POTENTIALLY')) return 'text-yellow-500';
    return 'text-green-500';
  };

  const VerdictIcon = data.verdict.includes('HIGHLY') || data.verdict.includes('POTENTIALLY')
    ? AlertTriangle
    : CheckCircle;

  const handleDownloadReport = () => {
    // Generate a comprehensive text report
    const reportContent = `
═══════════════════════════════════════════════════════════════
                    TRUTHGUARD AI ANALYSIS REPORT
═══════════════════════════════════════════════════════════════

ANALYSIS ID: ${data.id}
DATE: ${new Date(data.createdAt).toLocaleString()}
FILE: ${data.fileName}
SIZE: ${(data.fileSize / 1024 / 1024).toFixed(2)} MB
MODE: ${data.mode?.toUpperCase()}

───────────────────────────────────────────────────────────────
VERDICT: ${data.verdict}
───────────────────────────────────────────────────────────────

OVERALL MANIPULATION SCORE: ${data.overallScore}%

${data.overallScore > 70 ? '⚠️  HIGH RISK - Likely AI-generated or manipulated' :
  data.overallScore > 40 ? '⚡ MEDIUM RISK - Potential signs of manipulation' :
  '✓  LOW RISK - Likely authentic'}

───────────────────────────────────────────────────────────────
DETECTION BREAKDOWN
───────────────────────────────────────────────────────────────

${Object.entries(data.detections || {})
  .filter(([_, value]) => value !== null)
  .map(([key, value]) => {
    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
    return `${label}: ${value}%`;
  }).join('\n')}

───────────────────────────────────────────────────────────────
MODEL CONSENSUS
───────────────────────────────────────────────────────────────

Advanced Deepfake Detector: ${data.modelConsensus?.model1 || 'N/A'}%
Face Manipulation Analyzer: ${data.modelConsensus?.model2 || 'N/A'}%
Audio Synthesis Detector: ${data.modelConsensus?.model3 || 'N/A'}%
GAN Artifact Detector: ${data.modelConsensus?.model4 || 'N/A'}%

${data.issues && data.issues.length > 0 ? `
───────────────────────────────────────────────────────────────
DETECTED ISSUES
───────────────────────────────────────────────────────────────

${data.issues.map((issue: any, idx: number) => 
  `${idx + 1}. [${issue.time || issue.line || 'General'}] ${issue.issue} (${issue.severity?.toUpperCase()})`
).join('\n')}
` : ''}

───────────────────────────────────────────────────────────────
RECOMMENDATIONS
───────────────────────────────────────────────────────────────

${data.overallScore > 70 ? 
`• This content shows strong indicators of AI manipulation or generation
• Recommend further verification through additional sources
• Consider consulting forensic experts for critical use cases
• Do not use for authentication or legal purposes without expert review` :
data.overallScore > 40 ?
`• Some indicators of potential manipulation detected
• Review the specific issues flagged above
• Cross-reference with other verification methods
• Exercise caution when using this content` :
`• Content appears largely authentic
• No major manipulation indicators detected
• Standard verification practices still recommended
• Continue monitoring for emerging deepfake techniques`}

───────────────────────────────────────────────────────────────

Report generated by TruthGuard AI
Multi-Spectrum Deepfake Detection System

For questions or support, visit: https://truthguard.ai
───────────────────────────────────────────────────────────────
`;

    // Create and download the report file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TruthGuard_Report_${data.fileName}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    // Download raw JSON data
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TruthGuard_Data_${data.fileName}_${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = async () => {
    setGeneratingPDF(true);
    
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      let yPos = 20;
      
      // Helper function to add text
      const addText = (text: string, size: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
        pdf.setFontSize(size);
        pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
        pdf.setTextColor(color[0], color[1], color[2]);
        pdf.text(text, margin, yPos);
        yPos += size * 0.5;
      };
      
      const addLine = () => {
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 5;
      };
      
      const checkPageBreak = (neededSpace: number) => {
        if (yPos + neededSpace > pdf.internal.pageSize.getHeight() - margin) {
          pdf.addPage();
          yPos = 20;
        }
      };
      
      // Header
      pdf.setFillColor(59, 130, 246);
      pdf.rect(0, 0, pageWidth, 40, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(24);
      pdf.setFont('helvetica', 'bold');
      pdf.text('TRUTHGUARD AI', pageWidth / 2, 20, { align: 'center' });
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Deepfake Detection Report', pageWidth / 2, 30, { align: 'center' });
      
      yPos = 50;
      pdf.setTextColor(0, 0, 0);
      
      // Analysis Information
      addText('ANALYSIS REPORT', 16, true);
      yPos += 5;
      addLine();
      
      addText(`Analysis ID: ${data.id}`, 10);
      addText(`Date: ${new Date(data.createdAt).toLocaleString()}`, 10);
      addText(`File Name: ${data.fileName}`, 10);
      addText(`File Size: ${(data.fileSize / 1024 / 1024).toFixed(2)} MB`, 10);
      addText(`Detection Mode: ${data.mode?.toUpperCase()}`, 10);
      yPos += 5;
      
      // Verdict Section
      checkPageBreak(40);
      addLine();
      addText('VERDICT', 14, true);
      yPos += 2;
      
      const verdictColor: [number, number, number] = data.overallScore > 70 
        ? [220, 38, 38] // red
        : data.overallScore > 40 
        ? [234, 179, 8] // yellow
        : [34, 197, 94]; // green
      
      addText(data.verdict, 18, true, verdictColor);
      addText(`Overall Manipulation Score: ${data.overallScore}%`, 12, true, verdictColor);
      yPos += 5;
      
      // Risk Assessment
      const riskText = data.overallScore > 70 
        ? 'HIGH RISK - Likely AI-generated or manipulated'
        : data.overallScore > 40 
        ? 'MEDIUM RISK - Potential signs of manipulation'
        : 'LOW RISK - Likely authentic';
      addText(riskText, 11, false, verdictColor);
      yPos += 8;
      
      // Detection Breakdown
      checkPageBreak(60);
      addLine();
      addText('DETECTION BREAKDOWN', 14, true);
      yPos += 3;
      
      Object.entries(data.detections || {})
        .filter(([_, value]) => value !== null)
        .forEach(([key, value]) => {
          checkPageBreak(10);
          const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
          addText(`${label}: ${value}%`, 10);
        });
      yPos += 5;
      
      // Model Consensus
      checkPageBreak(50);
      addLine();
      addText('MODEL CONSENSUS', 14, true);
      yPos += 3;
      
      const models = [
        { name: 'Advanced Deepfake Detector', score: data.modelConsensus?.model1 },
        { name: 'Face Manipulation Analyzer', score: data.modelConsensus?.model2 },
        { name: 'Audio Synthesis Detector', score: data.modelConsensus?.model3 },
        { name: 'GAN Artifact Detector', score: data.modelConsensus?.model4 },
      ];
      
      models.forEach(model => {
        checkPageBreak(10);
        addText(`${model.name}: ${model.score}%`, 10);
      });
      yPos += 5;
      
      // Detected Issues
      if (data.issues && data.issues.length > 0) {
        checkPageBreak(40);
        addLine();
        addText('DETECTED ISSUES', 14, true);
        yPos += 3;
        
        data.issues.forEach((issue: any, idx: number) => {
          checkPageBreak(15);
          const location = issue.time || issue.line || issue.region || 'General';
          const severityColor: [number, number, number] = issue.severity === 'high' 
            ? [220, 38, 38] 
            : [234, 179, 8];
          
          addText(`${idx + 1}. [${location}] ${issue.issue}`, 10);
          addText(`   Severity: ${issue.severity?.toUpperCase()}`, 9, false, severityColor);
        });
        yPos += 5;
      }
      
      // Recommendations
      checkPageBreak(60);
      addLine();
      addText('RECOMMENDATIONS', 14, true);
      yPos += 3;
      
      const recommendations = data.overallScore > 70 
        ? [
            'This content shows strong indicators of AI manipulation or generation',
            'Recommend further verification through additional sources',
            'Consider consulting forensic experts for critical use cases',
            'Do not use for authentication or legal purposes without expert review'
          ]
        : data.overallScore > 40 
        ? [
            'Some indicators of potential manipulation detected',
            'Review the specific issues flagged above',
            'Cross-reference with other verification methods',
            'Exercise caution when using this content'
          ]
        : [
            'Content appears largely authentic',
            'No major manipulation indicators detected',
            'Standard verification practices still recommended',
            'Continue monitoring for emerging deepfake techniques'
          ];
      
      recommendations.forEach(rec => {
        checkPageBreak(10);
        pdf.setFontSize(10);
        const lines = pdf.splitTextToSize(`• ${rec}`, pageWidth - 2 * margin);
        pdf.text(lines, margin, yPos);
        yPos += lines.length * 5;
      });
      
      // Footer
      yPos = pdf.internal.pageSize.getHeight() - 20;
      pdf.setDrawColor(59, 130, 246);
      pdf.line(margin, yPos - 5, pageWidth - margin, yPos - 5);
      pdf.setFontSize(9);
      pdf.setTextColor(100, 100, 100);
      pdf.text('Report generated by TruthGuard AI - Multi-Spectrum Deepfake Detection System', pageWidth / 2, yPos, { align: 'center' });
      pdf.text('For questions or support, visit: https://truthguard.ai', pageWidth / 2, yPos + 5, { align: 'center' });
      
      // Save PDF
      pdf.save(`TruthGuard_Report_${data.fileName}_${new Date().toISOString().split('T')[0]}.pdf`);
      setGeneratingPDF(false);
    } catch (error) {
      console.error('PDF generation failed:', error);
      setGeneratingPDF(false);
      alert('Failed to generate PDF. Please try downloading the text report instead.');
    }
  };

  return (
    <div className="max-w-7xl">
      {/* Header */}
      <div className="mb-8 flex items-center justify-between">
        <button
          onClick={onReset}
          className="flex items-center gap-2 px-4 py-2 text-gray-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
          <span>New Analysis</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadReport}
            className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-medium transition-all"
          >
            <Download className="w-5 h-5" />
            <span>Download Report</span>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="flex items-center gap-2 px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white rounded-xl font-medium transition-all"
          >
            <Download className="w-5 h-5" />
            <span>Download JSON</span>
          </button>

          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white rounded-xl font-medium transition-all"
          >
            <Download className="w-5 h-5" />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      {/* Verdict Banner */}
      <motion.div
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        className={`relative overflow-hidden rounded-2xl p-8 mb-8 border-2 ${
          data.verdict.includes('HIGHLY') 
            ? 'border-red-500/50 bg-red-500/10' 
            : data.verdict.includes('POTENTIALLY')
            ? 'border-yellow-500/50 bg-yellow-500/10'
            : 'border-green-500/50 bg-green-500/10'
        }`}
      >
        <div className="flex items-start gap-6">
          <div className={`flex-shrink-0 w-16 h-16 rounded-2xl flex items-center justify-center ${
            data.verdict.includes('HIGHLY') 
              ? 'bg-red-500' 
              : data.verdict.includes('POTENTIALLY')
              ? 'bg-yellow-500'
              : 'bg-green-500'
          }`}>
            <VerdictIcon className="w-8 h-8 text-white" />
          </div>

          <div className="flex-1">
            <h2 className={`text-3xl font-bold mb-2 ${getVerdictColor(data.verdict)}`}>
              {data.verdict}
            </h2>
            <p className="text-gray-300 text-lg mb-2">
              File: <span className="font-mono text-white">{data.fileName}</span>
            </p>
            <p className="text-gray-400">
              Analysis completed • {data.mode?.toUpperCase()} mode
            </p>
          </div>

          <div className="flex-shrink-0 text-right">
            <div className="text-sm text-gray-400 mb-1">Manipulation Score</div>
            <div className={`text-5xl font-bold ${getVerdictColor(data.verdict)}`}>
              {data.overallScore}%
            </div>
          </div>
        </div>
      </motion.div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          <ScoreGauge score={data.overallScore} />
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="lg:col-span-2"
        >
          <DetectionBreakdown detections={data.detections} mode={data.mode} />
        </motion.div>
      </div>

      {/* Timeline Chart */}
      {data.timeline && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mb-8"
        >
          <TimelineChart data={data.timeline} mode={data.mode} />
        </motion.div>
      )}

      {/* Bottom Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <ModelConsensus models={data.modelConsensus} />
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <IssuesList issues={data.issues} />
        </motion.div>
      </div>
    </div>
  );
}